import { useCallback, useEffect, useState } from 'react'
import { format } from 'date-fns'
import { contractsAPI } from '../api/api'
import { Button } from './ui'

// The key-terms panel that opens under a contract row.
//
// Mounted only while open, and it fetches on mount: opening is the action that
// spends the GPU, so it must be a deliberate click rather than something a list
// render sets off across fifty rows. Re-opening refetches, but by then the
// server has the answer stored and the round trip is a database read.
const NONE = '—'

export default function ContractSummary({ fileId, token, canRefresh, onAuthError }) {
  const [state, setState] = useState({ loading: true, data: null, error: null, offline: false })

  const load = useCallback(async (refresh) => {
    setState((s) => ({ ...s, loading: true, error: null, offline: false }))
    try {
      const { data } = await contractsAPI.summarize(fileId, token, refresh)
      setState({ loading: false, data, error: null, offline: false })
    } catch (e) {
      if (onAuthError?.(e)) return
      setState({
        loading: false,
        data: null,
        offline: e.response?.data?.offline === true,
        // A timeout has no response body; say what actually happened rather
        // than the generic failure, because the two need different reactions.
        error: e.response?.data?.error || (e.code === 'ECONNABORTED' ? 'Timed out waiting for the local model' : 'Failed to summarise'),
      })
    }
  }, [fileId, token, onAuthError])

  useEffect(() => { load(false) }, [load])

  const { loading, data, error, offline } = state

  if (loading) {
    return (
      <div className="border-t border-slate-100 bg-slate-50 px-3 py-3 text-xs text-slate-500">
        Reading the contract… the first time takes up to a minute.
      </div>
    )
  }

  if (offline || error) {
    return (
      <div className="border-t border-slate-100 bg-slate-50 px-3 py-3 text-xs">
        <p className={offline ? 'text-amber-700' : 'text-rose-600'}>
          {offline ? 'The local model is offline right now — nothing was summarised.' : error}
        </p>
        <button onClick={() => load(false)} className="mt-1 font-semibold text-slate-500 hover:text-brand-600">Try again</button>
      </div>
    )
  }

  // Not an error, but nothing to show: the file has not been transcribed yet, or
  // it transcribed to nothing. Saying which one saves someone re-clicking.
  if (data?.reason === 'not-read' || data?.reason === 'no-readable-pages') {
    return (
      <div className="border-t border-slate-100 bg-slate-50 px-3 py-3 text-xs text-slate-500">
        {data.reason === 'not-read'
          ? 'This file has not been read by the local model yet, so there is nothing to summarise.'
          : 'Nothing readable came out of this file, so there is nothing to summarise.'}
      </div>
    )
  }

  const fields = data?.fields || []
  const found = fields.filter((f) => f.value && f.value !== NONE).length

  return (
    <div className="border-t border-slate-100 bg-slate-50 px-3 py-3">
      <dl className="grid gap-x-4 gap-y-1.5 sm:grid-cols-[auto_1fr]">
        {fields.map((f) => (
          <div key={f.key} className="contents">
            <dt className="text-xs font-semibold text-slate-500">{f.label}</dt>
            <dd className={`text-xs ${f.value === NONE ? 'text-slate-400' : 'text-slate-800'}`}>
              {f.value}
              {/* The page is the point: a term without one cannot be checked,
                  and these summaries are read before signing something. */}
              {f.source && <span className="ml-1.5 text-[11px] text-slate-400">{f.source}</span>}
            </dd>
          </div>
        ))}
      </dl>

      <div className="mt-2.5 flex flex-wrap items-center gap-2 text-[11px] text-slate-400">
        <span>
          {found}/{fields.length} found
          {data?.pages?.length ? ` · read pages ${data.pages.join(', ')}` : ''}
          {data?.summaryAt ? ` · ${format(new Date(data.summaryAt), 'yyyy-MM-dd HH:mm')}` : ''}
        </span>
        <span className="text-slate-300">Generated by a local model — check the cited page before relying on it.</span>
        {canRefresh && (
          <Button variant="secondary" size="sm" className="ml-auto" onClick={() => load(true)}>Regenerate</Button>
        )}
      </div>
    </div>
  )
}
