import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { tripsAPI } from '../api/api'
import { sortStopsByArrival } from '../utils/trips'
import TripMap from './TripMap'
import TripItinerary from './TripItinerary'
import TripPlanView from './TripPlanView'

// Public, login-free itinerary view reached via /trip/share/:token.
export default function TripShare() {
  const { token } = useParams()
  const [trip, setTrip] = useState(null)
  const [state, setState] = useState('loading') // loading | ready | notfound | error

  // Order stops by arrival so the map/list match the authenticated detail view.
  const stops = useMemo(() => sortStopsByArrival(trip?.stops), [trip])

  useEffect(() => {
    let ignore = false
    tripsAPI
      .getShared(token)
      .then((res) => {
        if (ignore) return
        setTrip(res.data)
        setState('ready')
      })
      .catch((err) => {
        if (ignore) return
        setState(err?.response?.status === 404 ? 'notfound' : 'error')
      })
    return () => {
      ignore = true
    }
  }, [token])

  if (state === 'loading') {
    return <p className="py-20 text-center text-slate-400">Loading...</p>
  }
  if (state === 'notfound') {
    return <p className="py-20 text-center text-slate-400">Trip not found or the link has expired.</p>
  }
  if (state === 'error') {
    return <p className="py-20 text-center text-slate-400">Failed to load. Please try again later.</p>
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="mx-auto max-w-[1000px] px-4 py-6 sm:py-8">
        <header className="mb-5">
          <p className="text-[11px] font-semibold uppercase tracking-[0.28em] text-slate-400">Shared itinerary</p>
          <h1 className="mt-1 text-2xl font-bold text-slate-800 sm:text-3xl">{trip.title}</h1>
          <p className="mt-1 text-sm text-slate-500">
            {new Date(trip.startTime).toLocaleString('en-US')} → {new Date(trip.endTime).toLocaleString('en-US')}
            {trip.assignee?.name ? ` · Assignee ${trip.assignee.name}` : ''}
          </p>
          {trip.notes && (
            <p className="mt-2 rounded-xl bg-white px-3.5 py-2.5 text-sm text-slate-600 ring-1 ring-slate-200">{trip.notes}</p>
          )}
        </header>

        <div className="mb-5">
          <TripMap stops={stops} height={420} />
        </div>

        {(trip.itinerary?.days?.length || (Array.isArray(trip.flights) && trip.flights.length)) && (
          <div className="mb-6">
            <TripPlanView trip={trip} />
          </div>
        )}

        <h2 className="mb-3 text-lg font-semibold text-slate-800">Visit order ({stops.length} stops)</h2>
        <TripItinerary stops={stops} />

        <p className="mt-8 text-center text-xs text-slate-400">Generated by Herkules CRM · Map: Google / AMap</p>
      </div>
    </div>
  )
}
